name: travel-planner-api
region: syd

services:
  - name: backend
    github:
      repo: dajesso/TravelPlanner_Pipeline
      branch: main
      deploy_on_push: true
    run_command: npm run dev
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://db-mongodb-syd1-49354-365d51c3.mongo.ondigitalocean.com/admin
      - key: JWT_SECRET
        value: felicisontheloose
