name: travelplanner
region: syd

services:
  - name: backend
    github:
      repo: dajesso/TravelPlanner_Pipeline
      branch: main
      deploy_on_push: true
    run_command: node src/index.js
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: felicisontheloose
      - key: MONGO_URI
        value: ${MONGO_URI}
