name: Digital Ocean Deployment

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

